"""empty message

Revision ID: 5917f111ac80
Revises: None
Create Date: 2015-07-07 19:43:56.448337

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '5917f111ac80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('mumble_password', sqlalchemy_utils.types.password.PasswordType(length=1024), nullable=True),
    sa.Column('main_character', sa.String(), nullable=True),
    sa.Column('main_character_id', sa.Integer(), nullable=True),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('alliance_name', sa.String(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('corporation_name', sa.String(), nullable=True),
    sa.Column('groups', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('last_ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.Column('last_login_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('guest_pass',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('expires_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('created_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(length=1024), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('corporation', sa.String(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('alliance', sa.String(), nullable=True),
    sa.Column('guest_pass_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('last_ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.Column('last_login_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('created_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_on', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['guest_pass_id'], ['guest_pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_user')
    op.drop_table('guest_pass')
    op.drop_table('user')
    ### end Alembic commands ###
